// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hykhgrfmyvsqckpbgpmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5a2hncmZteXZzcWNrcGJncG1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5ODU4NTgsImV4cCI6MjA3NDU2MTg1OH0.9CLm89RxBmd9q_R4HM2NWXPs6NVJO4G2b4hd-Qkfaf0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});